name: Build image

on: push

permissions:
  contents: write
  packages: write

jobs:
  build-image:
    uses: programie/Workflows/.github/workflows/build-docker-image.yml@main
    with:
      dockerhub_image: programie/php
    secrets: inherit

  create-release:
    needs: build-image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: CHANGELOG.md

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}